### ISSUE TITLE
Predictr has to stopped working

### ISSUE THREAD

**Issue by LoLei** [LoLei/sw-ss16#52]
```
05-03 11:38:41.668 5377-5377/com.sw_ss16.lc_app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sw_ss16.lc_app/com.sw_ss16.lc_app.ui.learning_center_list.ListActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:140)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4921)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                   Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:807)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                      at com.sw_ss16.lc_app.ui.learning_center_list.ListActivity.onCreate(ListActivity.java:36)
                                                                      at android.app.Activity.performCreate(Activity.java:5206)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) 
                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:140) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4921) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:807) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:736) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                      at com.sw_ss16.lc_app.ui.learning_center_list.ListActivity.onCreate(ListActivity.java:36) 
                                                                      at android.app.Activity.performCreate(Activity.java:5206) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) 
                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:140) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4921) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: java.lang.OutOfMemoryError
                                                                      at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                      at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:625)
                                                                      at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:478)
                                                                      at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:781)
                                                                      at android.content.res.Resources.loadDrawable(Resources.java:1963)
                                                                      at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                                                      at android.widget.ImageView.<init>(ImageView.java:120)
                                                                      at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:58)
                                                                      at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:54)
                                                                      at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:95)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:938)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:992)
                                                                      at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                      at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:190)
                                                                      at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:250)
                                                                      at android.support.design.widget.NavigationView.<init>(NavigationView.java:172)
                                                                    at android.support.design.wi
05-03 11:38:46.558 5377-5377/com.sw_ss16.lc_app I/Process: Sending signal. PID: 5377 SIG: 9
05-03 11:38:54.408 10134-10134/com.sw_ss16.lc_app W
```

**Comment by codecreativity** [comment]
fixed with adding all needed entries in DB
